### PR TITLE
Refactor to allow WP CLI command, add WP CLI command

### PR DESCRIPTION
**Pull request by simonwheatley**
Hi Konstantin,

Here is this evening's offering to your plugin: a WP CLI command. I needed to abstract the functionality and chose to do this into a singleton class, which I hope is OK.

Let me know any changes, or if this is something you are not interested in for your repo.

Thanks again for the work creating this!

Cheers,

Simon

### CODE REVIEW

**Comment by simonwheatley** [comment]
Oh, one fairly significant change: the code used to iterate in queries of 50 posts at a time. I changed this to just get everything at once, but to only retrieve IDs rather than _all_ the posts with NGG shortcodes. A little reckless? Let me know what you think.

**Comment by kovshenin** [comment]
So you removed `posts_per_page` and you removed the loop with the offset. I haven't tested it, but looks like i'll process a maximum of 10 posts, which is the default `posts_per_page`. I'm not a big fan of `posts_per_page` -1 because you can get in trouble when working with lots of data. Also, the offset loop I had implemented solves only half the problem, you'll need something like `clean_post_caches()` at each iteration, otherwise you end up consuming all the memory in the world, with or without posts_per_page -1.

Anyway, not a big deal at this point, but something to keep in mind. Without diving too much in your changes, please make sure you haven't limited the processing to a maximum of 10 posts. Other than that, I'm fine to merge, thanks for contributing!

**Comment by simonwheatley** [comment]
> So you removed `posts_per_page` and you removed the loop with the offset. I haven't tested it, but looks like i'll process a maximum of 10 posts, which is the default `posts_per_page`.

Yes, except I'm [setting `nopaging = true`](https://github.com/kovshenin/escape-ngg/pull/4/files#diff-83d638830146ac1ef0142de2be6229a9R253), which gets everything and is the equivalent of `posts_per_page = -1`.

> I'm not a big fan of posts_per_page -1 because you can get in trouble when working with lots of data.

Because we're only getting the IDs, not the full objects, in the query, I felt it might be possible to get away with it in most scenarios. I've tried it on site with 250 NGG shortcodes, and it was ran through them all… that's not many, really, but it's the largest data set I have to hand.

> …the offset loop I had implemented solves only half the problem, you'll need something like `clean_post_caches()` at each iteration, otherwise you end up consuming all the memory in the world…

I'll look at this and amend the pull request if it's useful.

**Comment by kovshenin** [comment]
Ah, nopaging, haven't seen that in a while, guess I feel like posts_per_page -1 is more explicit :)

> Because we're only getting the IDs, not the full objects, in the query

That's actually making it slower :) if you were getting the full posts objects, it would retrieve them all in a single query (well, four), but since you retrieved the IDs only, it'll go and fetch each post from the database again when you `get_post()` for every ID that you've fetched.

Yes, you're consuming less memory during the initial `WP_Query`, but consumption grows with every `get_post()` because it'll not only fetch the post from the database, but also stick it into the object cache, something you can by-pass in `WP_Query` with `cache_results`.

So my thinking with batches of 50 was: grab 50, process, clear caches, grab next 50, ...

All of this is not an issue with 250 posts. I don't think it'll be an issue with 5000 posts either, which is why I haven't bothered to implement the clearing caches part :) What was the peak memory consumption for 250 posts?

**Pull request merged**
